baseURL = "http://www.arthur-code-42.cc/"
defaultContentLanguage = "zh-cn"
title = "Arthur & Code & 42"
theme = "slim"
contentdir = "content"
layoutdir = "themes/slim/layouts"
publishdir = "public"
builddrafts = false
permalinks = "blog: /:year/:month/:title/"
canonifyurls = true
paginate=10
paginatePath="page"
[params]
  Subtitle = "记录代码、算法、架构和一切"
  Summary = true  # takes true or false
  Content = false  # takes true or false
  GithubID = "arthur"
[[menu.main]]
  name = "Coding"
  weight = 1
  url = "/"
[[menu.main]]
  name = "Reading"
  weight = 2
  url = "/"
[[menu.main]]
  name = "Recording"
  weight = 3
  url = "/"
[[menu.main]]
  name = "Cecording"
  weight = 4
  url = "/"

[[menu.main]]
  name = "About"
  weight = 5
  url = "/"